version: '3.8'

services:
  rides-server:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    container_name: rides-server
    depends_on:
      - rides-redis
      - rides-database
    environment:
      - PGDATABASE=rides
      - PGUSER=rides
      - PGPASSWORD=rides
      - PGHOST=rides-database
      - RIDES_URL=redis://rides-redis:6379/0
    ports:
      - 8003:8000
  
  rides-redis:
    container_name: rides-redis
    image: redis:6-alpine
  
  rides-database:
    container_name: rides-database
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=rides
      - POSTGRES_PASSWORD=rides
    expose:
      - 5432
    volumes:
      - rides-database:/var/lib/postgresql/data

volumes:
  rides-database:
    