# Generated by Django 4.0 on 2022-09-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('STARTED', 'STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=20),
        ),
    ]
